### ISSUE TITLE
Add clojars search fallback

### ISSUE THREAD

**Issue by johnwalker** [johnwalker/lein-plz#1]
<blockquote>

@arrdem: johnwalker: I just think it makes sense... ~80% of the time I know artifact ID but not always group ID. consequently being able to say `lein pls add ...` have search as a fallback would be amaze
</blockquote>

**Comment by mkremins** [comment]
I went digging around in the CrossClj javascript to figure out what exactly they were doing. Turns out they maintain an index of [around 4500 of the most popular Clojure projects](http://crossclj.info/api/v1/prefetch-home) which is relatively easy to parse. (The code that actually produces this index is, as far as I can tell, unpublished.)

I've put together a [proof-of-concept repo](https://github.com/mkremins/crossclj-search/blob/master/src/crossclj_search/core.clj) that grabs this index and parses it to produce a seq of maps representing popular projects. It then exposes a `search` function that takes a single string and returns a list of matching projects, ordered by relevance to the query and by popularity.

Depending on how you'd like to proceed, I could try putting together a pull request that uses this strategy to offer a fallback fuzzy-search option using CrossClj.

Advantages:
* Searches for `compojure`, `async`, `http`, `org.clojure/async`, `core-async` all return what you'd actually expect as the top result.

Disadvantages:
* You have to do an HTTP call to fetch the CrossClj index page.
* I'm not sure the CrossClj API is actually *meant* to be used externally like this considering they don't provide any kind of documentation. They might take it down or change the format without telling us, and we'd have to trust them to keep the index accurate and up-to-date.

**Comment by johnwalker** [comment]
Awesome. I definitely trust that crossclj will be around for a while, so we can ignore that for now. The other disadvantage can likely be mitigated by caching the index on disk. The index would be pretty nice as a fallback, since I'm pretty sure the plugin doesn't work when there is no network connection. I'm definitely interested in this approach.
